AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'spec/**/*'
    - 'test/**/*'
    - 'Gemfile'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Documentation:
    Enabled: false

NumericLiterals:
  MinDigits: 11