Rails:
  Enabled: true

Metrics/LineLength:

  Max: 120

Style/AsciiComments:

  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Documentation:
    Enabled: false

NumericLiterals:
  MinDigits: 11